-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "JobCategory" ADD VALUE 'AI_ML';
ALTER TYPE "JobCategory" ADD VALUE 'PROJECT_MANAGEMENT';
ALTER TYPE "JobCategory" ADD VALUE 'UI_UX_DESIGN';
ALTER TYPE "JobCategory" ADD VALUE 'DIGITAL_MARKETING';
ALTER TYPE "JobCategory" ADD VALUE 'CONTENT_WRITING';
ALTER TYPE "JobCategory" ADD VALUE 'SEO';
ALTER TYPE "JobCategory" ADD VALUE 'BUSINESS_DEVELOPMENT';
ALTER TYPE "JobCategory" ADD VALUE 'CUSTOMER_SUPPORT';
ALTER TYPE "JobCategory" ADD VALUE 'RECRUITMENT';
ALTER TYPE "JobCategory" ADD VALUE 'ACCOUNTING';
ALTER TYPE "JobCategory" ADD VALUE 'BANKING';
ALTER TYPE "JobCategory" ADD VALUE 'INVESTMENT';
ALTER TYPE "JobCategory" ADD VALUE 'OPERATIONS';
ALTER TYPE "JobCategory" ADD VALUE 'SUPPLY_CHAIN';
ALTER TYPE "JobCategory" ADD VALUE 'LOGISTICS';
ALTER TYPE "JobCategory" ADD VALUE 'LEGAL';
ALTER TYPE "JobCategory" ADD VALUE 'CONSULTING';
ALTER TYPE "JobCategory" ADD VALUE 'EDUCATION';
ALTER TYPE "JobCategory" ADD VALUE 'TRAINING';
ALTER TYPE "JobCategory" ADD VALUE 'HEALTHCARE';
ALTER TYPE "JobCategory" ADD VALUE 'PHARMACEUTICAL';
ALTER TYPE "JobCategory" ADD VALUE 'MECHANICAL_ENGINEERING';
ALTER TYPE "JobCategory" ADD VALUE 'ELECTRICAL_ENGINEERING';
ALTER TYPE "JobCategory" ADD VALUE 'CIVIL_ENGINEERING';
ALTER TYPE "JobCategory" ADD VALUE 'AUTOMOBILE';
ALTER TYPE "JobCategory" ADD VALUE 'TELECOMMUNICATION';
ALTER TYPE "JobCategory" ADD VALUE 'MEDIA';
ALTER TYPE "JobCategory" ADD VALUE 'JOURNALISM';
ALTER TYPE "JobCategory" ADD VALUE 'HOSPITALITY';
ALTER TYPE "JobCategory" ADD VALUE 'TRAVEL_TOURISM';
ALTER TYPE "JobCategory" ADD VALUE 'REAL_ESTATE';
ALTER TYPE "JobCategory" ADD VALUE 'GOVERNMENT';
ALTER TYPE "JobCategory" ADD VALUE 'INTERNSHIP';
